version: '2.2'
services:
  web:
    build: .
    ports:
     - "50001:5000"
    cpus: 0.8
    mem_limit: 4096M
    restart: on-failure
  redis:
    image: "redis:alpine"
    cpus: 0.8
    mem_limit: 4096M
    restart: on-failure
